version: '3'

volumes:
  db_data: {}

services:
  simplebank-database:
    image: "postgres:12-alpine"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
        - "5432:5432"
